name = "ASEC Gear";
dir = "@ASEC Gear";
author = "Jup, Lip, Thunder";
actionName = "";
action = "";
description = "Website: https://www.asecmilsim.com/";
tooltip = "ASEC Gear";
tooltipOwned = "ASEC Gear";
overview = "ASEC Gear";
overviewText = "ASEC Gear";
logoSmall	 = "ASECGearSmall.paa";	// Display next to the item added by the mod
logo		 = "ASECGear.paa";			// Logo displayed in the main menu
logoOver	 = "ASECGear.paa";	