class CfgPatches
{
	class VSM_G3_Config
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR"
		};
	};
};
class CfgVehicleClasses
{
	class VSM_G3
	{
		displayName="VSM G3";
	};
};
class cfgVehicles
{
	class NVGoggles;
	class Default;
	class ItemCore;
	class HeadgearItem;
	class InventoryItem_Base_F;
	class VSM_magpul_flightglove_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] Magpul Flight Gloves";
		model="\VSM_gloves\models\VSM_magpul_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_co.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="Magpul Flight Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_magpul_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_magpul_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_magpul_flightglove_coyote_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] Magpul Flight Gloves (coyote)";
		model="\VSM_gloves\models\VSM_magpul_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_coyote_co.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="Magpul Flight Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_magpul_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_magpul_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_magpul_flightglove_cut_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] Magpul Flight Gloves Cut";
		model="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_co.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="Magpul Flight Gloves Cut";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone.p3d";
			mass=1;
		};
	};
	class VSM_magpul_flightglove_cut_coyote_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] Magpul Flight Gloves Cut (coyote)";
		model="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_coyote_co.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="Magpul Flight Gloves Cut";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone.p3d";
			mass=1;
		};
	};
	class VSM_flightglove_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] Magpul Short-Cuff Flight Gloves";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_g2\Textures\VSM_flightgloves.rvmat"
		};
		picture="";
		class Library
		{
			libTextDesc="Flight Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_flightglove_coyote_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] Magpul Short-Cuff Flight Gloves (coyote)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_coyote_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_g2\Textures\VSM_flightgloves.rvmat"
		};
		picture="";
		class Library
		{
			libTextDesc="Flight Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_511_flightglove_coyote_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] 511 Gloves (coyote)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_g2\Textures\VSM_flightgloves_511.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="511 Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_511_flightglove_black_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] 511 Gloves (black)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_g2\Textures\VSM_flightgloves_511_black.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="511 Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_511_flightglove_od_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] 511 Gloves (OD)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_g2\Textures\VSM_flightgloves_511_od.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="511 Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_SPLAV_flightglove_coyote_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] SPLAV Gloves (coyote)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_SPLAV.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_splav.rvmat"
		};
		picture="";
		class Library
		{
			libTextDesc="SPLAV Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_SPLAV_flightglove_od_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] SPLAV Gloves (OD)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_SPLAV_OD.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_splav.rvmat"
		};
		picture="";
		class Library
		{
			libTextDesc="SPLAV Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			hiddenSelections[]=
			{
				"_MagpulGloves"
			};
			modelOff="\VSM_gloves\models\VSM_511_flightglove_standalone.p3d";
			mass=1;
		};
	};
	class VSM_MPACT_gloves_coyote_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] MPACT Gloves (coyote)";
		model="\VSM_gloves\models\VSM_MPACT_gloves_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_coyote.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="MPACT Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_MPACT_gloves_standalone.p3d";
			hiddenSelections[]=
			{
				"_MPACT"
			};
			modelOff="\VSM_gloves\models\VSM_MPACT_gloves_standalone.p3d";
			mass=1;
		};
	};
	class VSM_MPACT_gloves_black_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] MPACT Gloves (black)";
		model="\VSM_gloves\models\VSM_MPACT_gloves_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_black.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="MPACT Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_MPACT_gloves_standalone.p3d";
			hiddenSelections[]=
			{
				"_MPACT"
			};
			modelOff="\VSM_gloves\models\VSM_MPACT_gloves_standalone.p3d";
			mass=1;
		};
	};
	class VSM_MPACT_gloves_od_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] MPACT Gloves (OD)";
		model="\VSM_gloves\models\VSM_MPACT_gloves_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_OD.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="MPACT Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_MPACT_gloves_standalone.p3d";
			hiddenSelections[]=
			{
				"_MPACT"
			};
			modelOff="\VSM_gloves\models\VSM_MPACT_gloves_standalone.p3d";
			mass=1;
		};
	};
	class VSM_MPACT_gloves_cut_coyote_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] MPACT Gloves Cut (coyote)";
		model="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_coyote.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="MPACT Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone.p3d";
			hiddenSelections[]=
			{
				"_MPACT"
			};
			modelOff="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone.p3d";
			mass=1;
		};
	};
	class VSM_MPACT_gloves_cut_black_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] MPACT Gloves Cut (black)";
		model="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_black.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="MPACT Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone.p3d";
			hiddenSelections[]=
			{
				"_MPACT"
			};
			modelOff="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone.p3d";
			mass=1;
		};
	};
	class VSM_MPACT_gloves_cut_od_standalone_NVG: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] MPACT Gloves Cut (OD)";
		model="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_OD.paa"
		};
		picture="";
		class Library
		{
			libTextDesc="MPACT Gloves";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone.p3d";
			hiddenSelections[]=
			{
				"_MPACT"
			};
			modelOff="\VSM_gloves\models\VSM_MPACT_gloves_cut_standalone.p3d";
			mass=1;
		};
	};
	class VSM_NVG_Satchel: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] NVG Satchel";
		model="\VSM_gloves\models\VSM_NVG_Satchel_DOWN";
		picture="";
		class Library
		{
			libTextDesc="NVG Satchel";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_gloves\models\VSM_NVG_Satchel_DOWN.p3d";
			modelOff="\VSM_gloves\models\VSM_NVG_Satchel.p3d";
			mass=1;
		};
	};
	class VSM_gasmask_nvg: NVGoggles
	{
		author="VanSchmoozin";
		scope=0;
		displayName="[VSM] Gasmask";
		model="\VSM_Zenith_Headgear\models\VSM_gasmask";
		picture="";
		class Library
		{
			libTextDesc="NVG Gasmask";
		};
		class ItemInfo
		{
			type=616;
			hmdType=0;
			uniformModel="\VSM_Zenith_Headgear\models\VSM_gasmask";
			modelOff="\VSM_Zenith_Headgear\models\VSM_gasmask";
			mass=1;
		};
	};
};
class CfgGlasses
{
	class VSM_Scarf
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Scarf";
		model="\VSM_g3\models\VSM_scarf_2018";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_Gasmask_acc
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Gasmask";
		model="\VSM_Zenith_Headgear\models\VSM_gasmask";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_ghillie_standalone
	{
		scope=2;
		author="VanSchmoozin";
		displayname="[ASEC] Ghillie Suit";
		model="\VSM_g3\models\VSM_ghillie";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_ghillie_2_standalone
	{
		scope=2;
		author="VanSchmoozin";
		displayname="[ASEC] Lightweight Ghillie Suit";
		model="\VSM_g3\models\VSM_ghillie_2";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_ghillie_3_standalone
	{
		scope=2;
		author="VanSchmoozin";
		displayname="[ASEC] Ghillie Harness";
		model="\VSM_g3\models\VSM_ghillie_3";
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_magpul_flightglove_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Magpul Flight Gloves";
		model="\VSM_gloves\models\VSM_magpul_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_co.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_magpul_flightglove_coyote_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Magpul Flight Gloves (coyote)";
		model="\VSM_gloves\models\VSM_magpul_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_coyote_co.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_magpul_flightglove_cut_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Magpul Flight Gloves Cut";
		model="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_co.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_magpul_flightglove_cut_coyote_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Magpul Flight Gloves Cut (coyote)";
		model="\VSM_gloves\models\VSM_magpul_flightglove_cut_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_coyote_co.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_flightglove_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Flight Gloves";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_g2\Textures\VSM_flightgloves_magpul_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_g2\Textures\VSM_flightgloves.rvmat"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_flightglove_coyote_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] Flight Gloves (coyote_";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_flightgloves_magpul_coyote_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_g2\Textures\VSM_flightgloves.rvmat"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_511_flightglove_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] 511 Gloves (coyote)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_g2\Textures\VSM_flightgloves_511.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_511_flightglove_OD_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] 511 Gloves (OD) ";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_g2\Textures\VSM_flightgloves_511_OD.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_511_flightglove_Black_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] 511 Gloves (Black) ";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_g2\Textures\VSM_flightgloves_511_Black.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_SPLAV_flightglove_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] SPLAV Gloves (coyote)";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_splav.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_splav.rvmat"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_splav_flightglove_OD_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] SPLAV Gloves (OD) ";
		model="\VSM_gloves\models\VSM_511_flightglove_standalone";
		hiddenSelections[]=
		{
			"_MagpulGloves"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_SPLAV_OD.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"VSM_gorka\Textures\VSM_flightgloves_splav.rvmat"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_MPACT_Gloves_OD_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] MPACT Gloves (OD) ";
		model="\VSM_gloves\models\VSM_MPACT_Gloves_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_OD.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_MPACT_Gloves_coyote_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] MPACT Gloves (coyote) ";
		model="\VSM_gloves\models\VSM_MPACT_Gloves_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_coyote.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_MPACT_Gloves_black_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] MPACT Gloves (black) ";
		model="\VSM_gloves\models\VSM_MPACT_Gloves_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_black.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_MPACT_Gloves_cut_OD_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] MPACT Gloves Cut (OD) ";
		model="\VSM_gloves\models\VSM_MPACT_Gloves_cut_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_OD.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_MPACT_Gloves_cut_coyote_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] MPACT Gloves Cut (coyote) ";
		model="\VSM_gloves\models\VSM_MPACT_Gloves_cut_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_coyote.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class VSM_MPACT_Gloves_cut_black_standalone
	{
		scope=0;
		author="VanSchmoozin";
		displayname="[VSM] MPACT Gloves Cut (black) ";
		model="\VSM_gloves\models\VSM_MPACT_Gloves_cut_standalone";
		hiddenSelections[]=
		{
			"_MPACT"
		};
		hiddenSelectionsTextures[]=
		{
			"VSM_gloves\Textures\VSM_MPACT_gloves_black.paa"
		};
		picture="";
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
};
class cfgMods
{
	author="VanSchmoozin";
	timepacked="1528493143";
};
